services:
  muninn:
    extends:
      file: docker-compose.app.yml
      service: muninn

  friday-volume-init:
    extends:
      file: docker-compose.app.yml
      service: friday-volume-init

  friday-gateway-firewall:
    extends:
      file: docker-compose.app.yml
      service: friday-gateway-firewall

  friday-backend:
    extends:
      file: docker-compose.app.yml
      service: friday-backend
    depends_on:
      friday-volume-init:
        condition: service_completed_successfully
      muninn:
        condition: service_healthy
      friday-gateway-firewall:
        condition: service_completed_successfully

  friday-frontend:
    extends:
      file: docker-compose.app.yml
      service: friday-frontend
    depends_on:
      friday-backend:
        condition: service_healthy

  llm:
    extends:
      file: docker-compose.models.yml
      service: llm

networks:
  friday_net:
    name: friday_net
    driver: bridge

volumes:
  friday_data:
  friday_logs:
  muninn_data:
