#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
if [[ ! -f .env.runtime ]]; then
  cat > .env.runtime <<'EOF'
# Auto-generated by scripts/friday_up.sh
MUNINN_BASE_URL=
LLM_BASE_URL=
EOF
fi
docker compose -f docker-compose.models.yml down || true
docker compose -f docker-compose.app.yml down || true
