#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

APP_COMPOSE=${APP_COMPOSE:-docker-compose.app.yml}
MODELS_COMPOSE=${MODELS_COMPOSE:-docker-compose.models.yml}

# Preferences / defaults
HOST_MUNINN_URL_DEFAULT=${HOST_MUNINN_URL_DEFAULT:-http://127.0.0.1:8000}
HOST_LLM_URL_DEFAULT=${HOST_LLM_URL_DEFAULT:-http://127.0.0.1:8000}
HOST_LLM_URL_FALLBACK=${HOST_LLM_URL_FALLBACK:-http://127.0.0.1:8008}
COMPOSE_MUNINN_URL=${COMPOSE_MUNINN_URL:-http://muninn:8000}
COMPOSE_LLM_URL=${COMPOSE_LLM_URL:-http://llm:8000}
DOCKER_HOST_ALIAS=${DOCKER_HOST_ALIAS:-host.docker.internal}

AUTO_START_MODELS=${AUTO_START_MODELS:-1}
AUTO_START_MUNINN=${AUTO_START_MUNINN:-1}

probe_json() {
  local url="$1"
  curl -fsS --max-time 1 "$url" >/dev/null 2>&1
}

port_in_use() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -ltn "( sport = :${port} )" | awk 'NR>1 {found=1} END {exit(found?0:1)}'
  elif command -v lsof >/dev/null 2>&1; then
    lsof -iTCP:"${port}" -sTCP:LISTEN -nP >/dev/null 2>&1
  else
    nc -z 127.0.0.1 "${port}" >/dev/null 2>&1
  fi
}

choose_host_port() {
  local default_port="$1"
  local fallback_port="$2"
  local env_var_name="$3"
  local env_value="${!env_var_name-}"

  if [[ -n "${env_value}" ]]; then
    echo "${env_value}"
    return
  fi

  if port_in_use "${default_port}"; then
    echo "${fallback_port}"
  else
    echo "${default_port}"
  fi
}

to_container_url() {
  local url="$1"
  echo "$url" | sed -E "s#://(127\\.0\\.0\\.1|localhost)([:/])#://${DOCKER_HOST_ALIAS}\\2#"
}

choose_muninn_host_port() {
  if [[ "${MUNINN_BASE_URL}" == "${COMPOSE_MUNINN_URL}" ]]; then
    choose_host_port "8000" "18000" "FRIDAY_HOST_MUNINN_PORT"
  else
    # Avoid host-port collision when using external Muninn.
    echo "18000"
  fi
}

echo "==> FRIDAY autodiscovery"

MUNINN_BASE_URL=""
if probe_json "${HOST_MUNINN_URL_DEFAULT}/health"; then
  MUNINN_BASE_URL="$(to_container_url "${HOST_MUNINN_URL_DEFAULT}")"
  echo "Muninn: using host at ${MUNINN_BASE_URL}"
else
  if [[ "${AUTO_START_MUNINN}" == "1" ]]; then
    echo "Muninn: host not reachable; will use compose service (${COMPOSE_MUNINN_URL})"
    MUNINN_BASE_URL="${COMPOSE_MUNINN_URL}"
  else
    echo "Muninn: host not reachable and AUTO_START_MUNINN=0; leaving unset"
  fi
fi

LLM_BASE_URL=""
if probe_json "${HOST_LLM_URL_DEFAULT}/v1/models" || probe_json "${HOST_LLM_URL_DEFAULT}/health"; then
  LLM_BASE_URL="$(to_container_url "${HOST_LLM_URL_DEFAULT}")"
  echo "LLM: using host at ${LLM_BASE_URL}"
elif probe_json "${HOST_LLM_URL_FALLBACK}/v1/models" || probe_json "${HOST_LLM_URL_FALLBACK}/health"; then
  LLM_BASE_URL="$(to_container_url "${HOST_LLM_URL_FALLBACK}")"
  echo "LLM: using host at ${LLM_BASE_URL}"
else
  if [[ "${AUTO_START_MODELS}" == "1" ]]; then
    echo "LLM: host not reachable; will use compose model service (${COMPOSE_LLM_URL})"
    LLM_BASE_URL="${COMPOSE_LLM_URL}"
  else
    echo "LLM: host not reachable and AUTO_START_MODELS=0; leaving unset"
  fi
fi

cat > .env.runtime <<EOF
# Auto-generated by scripts/friday_up.sh
MUNINN_BASE_URL=${MUNINN_BASE_URL}
LLM_BASE_URL=${LLM_BASE_URL}
EOF

echo "==> Wrote .env.runtime"
sed -n '1,120p' .env.runtime

RESOLVED_MUNINN_HOST_PORT="$(choose_muninn_host_port)"
RESOLVED_API_HOST_PORT="$(choose_host_port "9001" "19001" "FRIDAY_HOST_API_PORT")"
RESOLVED_WEB_HOST_PORT="$(choose_host_port "8080" "18080" "FRIDAY_HOST_WEB_PORT")"
USE_COMPOSE_MUNINN=0
if [[ "${MUNINN_BASE_URL}" == "${COMPOSE_MUNINN_URL}" ]]; then
  USE_COMPOSE_MUNINN=1
fi

if [[ -z "${FRIDAY_HOST_API_PORT:-}" ]] && [[ "${RESOLVED_API_HOST_PORT}" != "9001" ]]; then
  echo "Backend port 9001 busy; using ${RESOLVED_API_HOST_PORT}"
fi
if [[ -z "${FRIDAY_HOST_WEB_PORT:-}" ]] && [[ "${RESOLVED_WEB_HOST_PORT}" != "8080" ]]; then
  echo "Frontend port 8080 busy; using ${RESOLVED_WEB_HOST_PORT}"
fi

echo "==> Starting app stack: ${APP_COMPOSE}"
if [[ "${USE_COMPOSE_MUNINN}" == "1" ]]; then
  FRIDAY_HOST_API_PORT="${RESOLVED_API_HOST_PORT}" \
  FRIDAY_HOST_WEB_PORT="${RESOLVED_WEB_HOST_PORT}" \
  FRIDAY_HOST_MUNINN_PORT="${RESOLVED_MUNINN_HOST_PORT}" \
    docker compose -f "${APP_COMPOSE}" up -d --build
else
  echo "==> Starting backend/frontend only (external Muninn or disabled Muninn)"
  FRIDAY_HOST_API_PORT="${RESOLVED_API_HOST_PORT}" \
  FRIDAY_HOST_WEB_PORT="${RESOLVED_WEB_HOST_PORT}" \
  FRIDAY_HOST_MUNINN_PORT="${RESOLVED_MUNINN_HOST_PORT}" \
    docker compose -f "${APP_COMPOSE}" up -d --build --no-deps friday-backend friday-frontend
fi

if [[ "${AUTO_START_MODELS}" == "1" ]] && [[ "${LLM_BASE_URL}" == "${COMPOSE_LLM_URL}" ]]; then
  echo "==> Starting models stack: ${MODELS_COMPOSE}"
  docker compose -f "${MODELS_COMPOSE}" --profile models up -d || true
fi

echo "==> Done. Frontend: http://127.0.0.1:${RESOLVED_WEB_HOST_PORT}  Backend: http://127.0.0.1:${RESOLVED_API_HOST_PORT}  Muninn: ${MUNINN_BASE_URL}  LLM: ${LLM_BASE_URL}"
