#!/usr/bin/env bash
set -euo pipefail

# FRIDAY model fetcher (HF + GitHub)
# Expects: HF_TOKEN in env (exported in bashrc is fine)

ROOT_DIR="${ROOT_DIR:-$(pwd)}"
MODELS_DIR="${MODELS_DIR:-$ROOT_DIR/services/models}"
REPOS_DIR="${REPOS_DIR:-$ROOT_DIR/services/repos}"

# Toggle downloads (1=on, 0=off)
DL_CORE_LLM="${DL_CORE_LLM:-1}"
DL_CODER="${DL_CODER:-1}"
DL_VLM="${DL_VLM:-1}"
DL_OMNI="${DL_OMNI:-1}"
DL_STT="${DL_STT:-1}"

# Optional: pin exact model IDs here
CORE_LLM_ID="${CORE_LLM_ID:-Qwen/Qwen3-32B-FP8}"
CODER_ID="${CODER_ID:-Qwen/Qwen3-Coder-30B-A3B-Instruct-FP8}"
VLM_ID="${VLM_ID:-Qwen/Qwen3-VL-32B-Instruct-FP8}"
OMNI_ID="${OMNI_ID:-Qwen/Qwen3-Omni-30B-A3B-Instruct}"
STT_ID="${STT_ID:-Systran/faster-whisper-large-v3}"

# ---- helpers ----
need_cmd() { command -v "$1" >/dev/null 2>&1 || { echo "Missing required command: $1" >&2; exit 1; }; }

ensure_dirs() {
  mkdir -p "$MODELS_DIR"/{llm,code,vlm,omni,stt}
  mkdir -p "$REPOS_DIR"
}

ensure_hf_cli() {
  if ! command -v huggingface-cli >/dev/null 2>&1; then
    echo "[+] Installing huggingface_hub CLI (pip)..."
    python3 -m pip install --upgrade pip >/dev/null
    python3 -m pip install --upgrade huggingface_hub >/dev/null
  fi
}

hf_login_if_needed() {
  if [[ -z "${HF_TOKEN:-}" ]]; then
    echo "ERROR: HF_TOKEN is not set. Export it (e.g. in ~/.bashrc) and re-run." >&2
    exit 1
  fi
  # Avoid interactive login; use token directly.
  export HF_TOKEN
}

hf_pull() {
  local model_id="$1"
  local out_dir="$2"
  echo "[+] Downloading $model_id -> $out_dir"
  mkdir -p "$out_dir"
  huggingface-cli download "$model_id" \
    --local-dir "$out_dir" \
    --local-dir-use-symlinks False
}

git_clone_if_missing() {
  local url="$1"
  local name="$2"
  local target="$REPOS_DIR/$name"
  if [[ -d "$target/.git" ]]; then
    echo "[=] Repo exists: $target"
    return 0
  fi
  echo "[+] Cloning $url -> $target"
  git clone --depth 1 "$url" "$target"
}

write_manifest() {
  local manifest="$MODELS_DIR/MODEL_MANIFEST.env"
  cat > "$manifest" <<MANIFEST
# Auto-generated by tools/pull_models.sh
FRIDAY_LLM_MODEL_DIR=$MODELS_DIR/llm/qwen3-32b-fp8
FRIDAY_CODER_MODEL_DIR=$MODELS_DIR/code/qwen3-coder-30b-a3b-fp8
FRIDAY_VLM_MODEL_DIR=$MODELS_DIR/vlm/qwen3-vl-32b-fp8
FRIDAY_OMNI_MODEL_DIR=$MODELS_DIR/omni/qwen3-omni-30b-a3b
FRIDAY_STT_MODEL_DIR=$MODELS_DIR/stt/faster-whisper-large-v3

# Suggested service URLs (when you stand up vLLM containers later)
# FRIDAY_LLM_BASE_URL=http://llm-core:8000/v1
# FRIDAY_CODER_BASE_URL=http://llm-coder:8000/v1
# FRIDAY_VLM_BASE_URL=http://vlm:8000/v1
# FRIDAY_OMNI_BASE_URL=http://omni:8000/v1
# FRIDAY_STT_BASE_URL=http://stt:8001
MANIFEST
  echo "[+] Wrote $manifest"
}

# ---- main ----
need_cmd git
need_cmd python3

ensure_dirs
ensure_hf_cli
hf_login_if_needed

# Pull models (HF)
if [[ "$DL_CORE_LLM" == "1" ]]; then
  hf_pull "$CORE_LLM_ID" "$MODELS_DIR/llm/qwen3-32b-fp8"
fi

if [[ "$DL_CODER" == "1" ]]; then
  hf_pull "$CODER_ID" "$MODELS_DIR/code/qwen3-coder-30b-a3b-fp8"
fi

if [[ "$DL_VLM" == "1" ]]; then
  hf_pull "$VLM_ID" "$MODELS_DIR/vlm/qwen3-vl-32b-fp8"
fi

if [[ "$DL_OMNI" == "1" ]]; then
  hf_pull "$OMNI_ID" "$MODELS_DIR/omni/qwen3-omni-30b-a3b"
fi

if [[ "$DL_STT" == "1" ]]; then
  hf_pull "$STT_ID" "$MODELS_DIR/stt/faster-whisper-large-v3"
fi

# Clone useful repos (GitHub)
git_clone_if_missing "https://github.com/QwenLM/Qwen3-VL" "Qwen3-VL"
git_clone_if_missing "https://github.com/QwenLM/Qwen3-Coder" "Qwen3-Coder"
git_clone_if_missing "https://github.com/SYSTRAN/faster-whisper" "faster-whisper"

write_manifest

echo
echo "[✓] Done."
echo "Next: source services/models/MODEL_MANIFEST.env into your .env (or copy paths)."
